#! /bin/bash

dir=$1
RESULT=`ls -a $dir | sort`
declare -a ARRAY
let count=0
IFS=$'\n'
for file in $RESULT
do
if [[ ! -r "$dir/$FILE" ]]
then
echo "$dir/$FILE is not readable"
elif [[ ! -L "$dir/$FILE" ]]
then
if [[ -f "$dir/$FILE" ]]
then
echo "$dir/$FILE is a regular file"
ARRAY[$count]="$dir/$FILE"
let count=count+1
else
echo "$dir/$FILE is NOT a regular file"
fi
fi
done
echo "There are $count regular files"
for (( i=0; i<$count; i++ ))
do
for (( j=i+1; j<$count; j++ ))
do
cmp -s "${ARRAY[$i]}" "${ARRAY[$j]}"
if [[ $? -eq 0 ]]
then
if [[ "${ARRAY[$i]}" < "${ARRAY[$j]}" ]]
then
ln "${ARRAY[$i]}" "${ARRAY[$j]}"
rm "${ARRAY[$j]}"
else
ln "${ARRAY[$j]}" "${ARRAY[$i]}"
rm "${ARRAY[$i]}"
fi
fi
done
done